### PR TITLE
New config for Wikipathways

### PR DESCRIPTION
**Pull request by egonw**
Hi, I watched the https://www.youtube.com/watch?v=IJHyjdoSN54 recording today and excited about the progress being made. As I wanted to learn the `Qleverfile` idea, I created one for WikiPathways. I notice the format is not quite like that of the other files in this folder, and like to request feedback. For example, it's a bit hacky, as WikiPathways release their RDF as three zip files and one turtle file. Also, in the `sparql.wikipathways.org` endpoint, we also have ontologies loaded, which I will want to add at some point too. Final point, I want to try to replace the `RELEASE` with `current` instead of a date. But that will require some more work, the 'current' does not include the RDF anyway (to be fixed).

When it is fine, I am hoping you want to include this at some point.

### CODE REVIEW

**Comment by hannahbast** [comment]
@egonw Thanks for this PR and the pointer to this interesting dataset. I have a couple of questions:

1. Why is the RDF data spread over so many different files? It would be better practice to provide the data as a single file.

2. It's only around 20 M triples. Shouldn't this be a part of Wikidata? Are there many links to Wikidata?

3. How is this related to datasets like [PubChem](https://pubchem.ncbi.nlm.nih.gov/docs/rdf/) and [UniProt](https://sparql.uniprot.org/)? Are there any links or should there be?

**Comment by hannahbast** [comment]
@egonw Two more things:

4. I have set up a SPARQL endpoint: https://qlever.cs.uni-freiburg.de/wikipathways . Feel free to play around with it (in particular, the autocompletion) and let me know whether you find any problems.

5. Do you have a list of example queries?

It looks like a very nice and interesting dataset!

**Comment by egonw** [comment]
> @egonw Thanks for this PR and the pointer to this interesting dataset. I have a couple of questions:

Thanks for the quick reply!

> 1. Why is the RDF data spread over so many different files? It would be better practice to provide the data as a single file.

Partly historic, partly on purpose. The WikiPathways RDF consists of two parts, the GPMLRDF with an almost literal conversion of the biological pathway in GPML format to RDF, with all the graphics details, while the WPRDF extracts the biological meaning and is much simpler to navigate.

> 2. It's only around 20 M triples. Shouldn't this be a part of Wikidata? Are there many links to Wikidata?

Part of it is actually in Wikidata (Thanks to Andra), but WikiPathways has much more. Notability in Wikidata is an issue.

There are indeed links to Wikidata, tho at this moment mostly for the small compounds (metabolites, drugs, etc).

> 3. How is this related to datasets like [PubChem](https://pubchem.ncbi.nlm.nih.gov/docs/rdf/) and [UniProt](https://sparql.uniprot.org/)? Are there any links or should there be?

Complementary indeed. We have links to both in the RDF. For UniProt/Nextprot we have developed federated queries in the past. For PubChem some, via the IDSM.

> 4. I have set up a SPARQL endpoint: https://qlever.cs.uni-freiburg.de/wikipathways . 

Oh, great! 

> Feel free to play around with it (in particular, the autocompletion) and let me know whether you find any problems.

Will do!

> 5. Do you have a list of example queries?

Yes, Ammar had set up a Snorql derivative with example queries: https://sparql.wikipathways.org/

They get automatically pulled from this GitHub repo: https://github.com/wikipathways/SPARQLQueries

**Comment by hannahbast** [comment]
A Qleverfile for WikiPathways was added six months ago with 5d565c57a9130333df8b5c89106a0cf9f8258584 and updated just now with 4bb153fd6cfeb6597955aa34c0d18a95c675b221

**Comment by egonw** [comment]
The RELEASE info is actually in the VoID header file, and the latest version is always in this URL: https://data.wikipathways.org/current/rdf/wikipathways-rdf-void.ttl

I just need to update this QLeverfile to extract the download URLs for the files from the VoID header file... I have code for that, but just need to integrate that. The Python code I have used before is here: https://colab.research.google.com/drive/126diGs9webJcbl6qgPGLtOKyOO_40YmH#scrollTo=Vq9-oxvrfSR8

**Pull request closed without merging**
